/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "utils.h"

char *host;
CLIENT *clnt;

//void rpcdbprog_1() {
//
//	CLIENT *clnt;
//	package  *result_1;
//	package  add_1_arg;
//	package  *result_2;
//	package  update_1_arg;
//	package  *result_3;
//	package  del_1_arg;
//	package  *result_4;
//	package  read_1_arg;
//	package  *result_5;
//	package  get_stat_1_arg;
//	package  *result_6;
//	package  get_stat_all_1_arg;
//	package  *result_7;
//	char *load_1_arg;
//	package  *result_8;
//	char *store_1_arg;
//
//	clnt = clnt_create (host, RPCDBPROG, RPCDBVERS, "udp");
//	if (clnt == NULL) {
//		clnt_pcreateerror (host);
//		exit (1);
//	}
//
//	result_1 = add_1(&add_1_arg, clnt);
//	if (result_1 == (package *) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
//	result_2 = update_1(&update_1_arg, clnt);
//	if (result_2 == (package *) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
//	result_3 = del_1(&del_1_arg, clnt);
//	if (result_3 == (package *) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
//	result_4 = read_1(&read_1_arg, clnt);
//	if (result_4 == (package *) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
//	result_5 = get_stat_1(&get_stat_1_arg, clnt);
//	if (result_5 == (package *) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
//	result_6 = get_stat_all_1(&get_stat_all_1_arg, clnt);
//	if (result_6 == (package *) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
//	result_7 = load_1((void*)&load_1_arg, clnt);
//	if (result_7 == (package *) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
//	result_8 = store_1((void*)&store_1_arg, clnt);
//	if (result_8 == (package *) NULL) {
////		clnt_perror (clnt, "call failed");
////	}
//
//	clnt_destroy (clnt);
//}

FILE* get_commands_input(int argc, char *argv[]) {
	FILE *commannds_file = NULL;

	printf("Getting commands input...\n");
	if (argc == 3) {
        commannds_file = fopen (argv[2], "r");
    } else {
        commannds_file = stdin;
    }

	if (commannds_file == NULL) {
        printf("[ERROR] Could not open commands file!\n");
        exit(1);
    }

	return(commannds_file);
}

void login(char *command) {
	char *user;

	printf("Connecting to host '%s'...\n", host);
	clnt = clnt_create (host, RPCDBPROG, RPCDBVERS, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        exit (1);
    }

    user = strtok(command, " ");
    printf("Trying to log in with user '%s'...\n", command);
}

void execute_commands(FILE *commannds_file) {
	char line[MAX_BUF], *command;

	printf("Executing commands...\n");
	while (fgets (line, MAX_BUF, commannds_file) != NULL) {
		command = strtok (line, " \n");
		if (command == NULL) {
			break;
		}
		printf("Received '%s' command request\n", command);

		if (strcmp(command, LOGIN_COMMAND) == 0) {
			login(strtok (NULL, "\n"));
		} else if (strcmp(command, LOGOUT_COMMAND) == 0) {
		} else if (strcmp(command, ADD_COMMAND) == 0) {
		} else if (strcmp(command, DEL_COMMAND) == 0) {
		} else if (strcmp(command, UPDATE_COMMAND) == 0) {
		} else if (strcmp(command, READ_COMMAND) == 0) {
		} else if (strcmp(command, GET_STAT_COMMAND) == 0) {
		} else if (strcmp(command, GET_STAT_ALL_COMMAND) == 0) {
		} else if (strcmp(command, STORE_COMMAND) == 0) {
		} else if (strcmp(command, LOAD_COMMAND) == 0) {
		} else {
			printf("[ERROR] Could not process command '%s'\n", line);
		}
    }
}


int main (int argc, char *argv[]) {
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];

	FILE *commannds_file;
	commannds_file = get_commands_input(argc, argv);
	execute_commands(commannds_file);



//	rpcdbprog_1 (argv[1]);

	return(0);
}
