/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

prime_result *find_primes_1_svc(prime_request *request) {
	static prime_result  result;

    result.sum = request->a + request->b;

	return &result;
}
