/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcdb.h"

bool_t
xdr_sensor_data (XDR *xdrs, sensor_data *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->data_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->no_values))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->array.array_val, (u_int *) &objp->array.array_len, MAXBUF,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_statistics (XDR *xdrs, statistics *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->min))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->max))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->avg))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->med))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->min);
			IXDR_PUT_LONG(buf, objp->max);
			IXDR_PUT_LONG(buf, objp->avg);
			IXDR_PUT_LONG(buf, objp->med);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->min))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->max))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->avg))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->med))
				 return FALSE;
		} else {
			objp->min = IXDR_GET_LONG(buf);
			objp->max = IXDR_GET_LONG(buf);
			objp->avg = IXDR_GET_LONG(buf);
			objp->med = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->avg))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->med))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_package (XDR *xdrs, package *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_u_quad_t (xdrs, &objp->token))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->command, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->message, ~0))
		 return FALSE;
	 if (!xdr_sensor_data (xdrs, &objp->data))
		 return FALSE;
	 if (!xdr_statistics (xdrs, &objp->stats))
		 return FALSE;
	return TRUE;
}
