/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpcdb.h"

package* command_1_svc(package *argp, struct svc_req *rqstp) {
	static package  result;

	result.command = "";
    result.message = "";
    static float values[MAXBUF];
	result.data.array.array_len = 0;
    result.data.array.array_val = values;

	return &result;
}
