/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCDB_H_RPCGEN
#define _RPCDB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sensor_data {
	int data_id;
	int no_values;
	float *values;
};
typedef struct sensor_data sensor_data;

struct statistics {
	int min;
	int max;
	int avg;
	int med;
};
typedef struct statistics statistics;

struct package {
	int id;
	u_long token;
	char *message;
	struct sensor_data data;
	struct statistics stats;
};
typedef struct package package;

#define RPCDBPROG 0x31234567
#define RPCDBVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOGIN 1
extern  package * login_1(package *, CLIENT *);
extern  package * login_1_svc(package *, struct svc_req *);
#define LOGOUT 2
extern  package * logout_1(package *, CLIENT *);
extern  package * logout_1_svc(package *, struct svc_req *);
#define ADD 3
extern  package * add_1(package *, CLIENT *);
extern  package * add_1_svc(package *, struct svc_req *);
#define UPDATE 4
extern  package * update_1(package *, CLIENT *);
extern  package * update_1_svc(package *, struct svc_req *);
#define DEL 5
extern  package * del_1(package *, CLIENT *);
extern  package * del_1_svc(package *, struct svc_req *);
#define READ 6
extern  package * read_1(package *, CLIENT *);
extern  package * read_1_svc(package *, struct svc_req *);
#define GET_STAT 7
extern  package * get_stat_1(package *, CLIENT *);
extern  package * get_stat_1_svc(package *, struct svc_req *);
#define GET_STAT_ALL 8
extern  package * get_stat_all_1(package *, CLIENT *);
extern  package * get_stat_all_1_svc(package *, struct svc_req *);
#define LOAD 9
extern  package * load_1(void *, CLIENT *);
extern  package * load_1_svc(void *, struct svc_req *);
#define STORE 10
extern  package * store_1(void *, CLIENT *);
extern  package * store_1_svc(void *, struct svc_req *);
extern int rpcdbprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOGIN 1
extern  package * login_1();
extern  package * login_1_svc();
#define LOGOUT 2
extern  package * logout_1();
extern  package * logout_1_svc();
#define ADD 3
extern  package * add_1();
extern  package * add_1_svc();
#define UPDATE 4
extern  package * update_1();
extern  package * update_1_svc();
#define DEL 5
extern  package * del_1();
extern  package * del_1_svc();
#define READ 6
extern  package * read_1();
extern  package * read_1_svc();
#define GET_STAT 7
extern  package * get_stat_1();
extern  package * get_stat_1_svc();
#define GET_STAT_ALL 8
extern  package * get_stat_all_1();
extern  package * get_stat_all_1_svc();
#define LOAD 9
extern  package * load_1();
extern  package * load_1_svc();
#define STORE 10
extern  package * store_1();
extern  package * store_1_svc();
extern int rpcdbprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sensor_data (XDR *, sensor_data*);
extern  bool_t xdr_statistics (XDR *, statistics*);
extern  bool_t xdr_package (XDR *, package*);

#else /* K&R C */
extern bool_t xdr_sensor_data ();
extern bool_t xdr_statistics ();
extern bool_t xdr_package ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCDB_H_RPCGEN */
