/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCDB_H_RPCGEN
#define _RPCDB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXBUF 1000

struct sensor_data {
	int data_id;
	int no_values;
	struct {
		u_int array_len;
		float *array_val;
	} array;
};
typedef struct sensor_data sensor_data;

struct statistics {
	int min;
	int max;
	int avg;
	int med;
};
typedef struct statistics statistics;

struct package {
	int id;
	u_quad_t token;
	char *command;
	char *message;
	struct sensor_data data;
	struct statistics stats;
};
typedef struct package package;

#define RPCDBPROG 0x32345678
#define RPCDBVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define COMMAND 1
extern  package * command_1(package *, CLIENT *);
extern  package * command_1_svc(package *, struct svc_req *);
extern int rpcdbprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define COMMAND 1
extern  package * command_1();
extern  package * command_1_svc();
extern int rpcdbprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sensor_data (XDR *, sensor_data*);
extern  bool_t xdr_statistics (XDR *, statistics*);
extern  bool_t xdr_package (XDR *, package*);

#else /* K&R C */
extern bool_t xdr_sensor_data ();
extern bool_t xdr_statistics ();
extern bool_t xdr_package ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCDB_H_RPCGEN */
