/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <inttypes.h>

#define LOGIN_COMMAND "login"
#define LOGOUT_COMMAND "logout"
#define ADD_COMMAND "add"
#define DEL_COMMAND "del"
#define UPDATE_COMMAND "update"
#define READ_COMMAND "read"
#define GET_STAT_COMMAND "get_stat"
#define GET_STAT_ALL_COMMAND "get_stat_all"
#define STORE_COMMAND "store"
#define LOAD_COMMAND "load"

#define REJECTED_TOKEN -1
#define BLANK -1
#define EMPTY ""
#define ERROR "ERROR"

#ifndef _RPCDB_H_RPCGEN
#define _RPCDB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXBUF 1000
#define INF 999999

struct sensor_data {
	int data_id;
	int no_values;
	struct {
		u_int array_len;
		float *array_val;
	} array;
};
typedef struct sensor_data sensor_data;

struct statistics {
	int min;
	int max;
	int avg;
	int med;
};
typedef struct statistics statistics;

struct package {
	int id;
	u_quad_t token;
	char *command;
	char *message;
	struct sensor_data data;
	struct statistics stats;
};
typedef struct package package;

// data kept in server  ////////////////////////////
struct memory_database {
	struct sensor_data data;
	struct memory_database *next;
};
typedef struct memory_database memory_database;

struct user_data {
	char* user_name;
	u_quad_t token;
	struct memory_database *mem_database;
	FILE* disk_database;
};
typedef struct user_data user_data;

struct users {
	struct user_data user;
	struct users *next;
};
typedef struct users users;
////////////////////////////////////////////////////////

#define RPCDBPROG 0x32345678
#define RPCDBVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define COMMAND 1
extern  package * command_1(package *, CLIENT *);
extern  package * command_1_svc(package *, struct svc_req *);
extern int rpcdbprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define COMMAND 1
extern  package * command_1();
extern  package * command_1_svc();
extern int rpcdbprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sensor_data (XDR *, sensor_data*);
extern  bool_t xdr_statistics (XDR *, statistics*);
extern  bool_t xdr_package (XDR *, package*);

#else /* K&R C */
extern bool_t xdr_sensor_data ();
extern bool_t xdr_statistics ();
extern bool_t xdr_package ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCDB_H_RPCGEN */
