/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpcdb.h"


void rpcdbprog_1(char *host) {
	CLIENT *clnt;
	package  *result_1;
	package  command_1_arg;

	clnt = clnt_create (host, RPCDBPROG, RPCDBVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	command_1_arg.command = "";
    command_1_arg.message = "";
    static float values[MAXBUF];
    command_1_arg.data.array.array_len = 0;
    command_1_arg.data.array.array_val = values;

	result_1 = command_1(&command_1_arg, clnt);
	if (result_1 == (package *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	clnt_destroy (clnt);
}


int main (int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	rpcdbprog_1 (host);

	exit (0);
}
