/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int main(int argc, char *argv[]) {
	int i;
	CLIENT *cl;
	prime_result *result;
	prime_request request;

	if (argc != 4){
		printf("usage: %s host a b\n", argv[0]);
		exit(1);
	}

	cl = clnt_create(argv[1], PRIMEPROG, PRIMEVERS, "tcp");
	if (cl == NULL) {
		clnt_pcreateerror(argv[1]);
		exit(2);
	}

	request.a = atoi(argv[2]);
    request.b = atoi(argv[3]);

    result = find_primes_1(&request, cl);
    if (result == NULL){
	    clnt_perror(cl, argv[1]);
	    exit(3);
    }

    printf("Sum = %d\n", result->sum);

//    xdr_free(xdr_prime_result, result);
    clnt_destroy(cl);

	return 0;
}
