/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "add.h"

bool_t
xdr_prime_request (XDR *xdrs, prime_request *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_prime_result (XDR *xdrs, prime_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->sum))
		 return FALSE;
	return TRUE;
}
