/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ex.h"

int main(int argc, char *argv[]) {
	int i;
	CLIENT *cl;

	rezultat *rezult;
	student stud;

	cl = clnt_create("sprc2.dfilip.xyz", CHECKPROG, CHECKVERS, "tcp");
	if (cl == NULL) {
		clnt_pcreateerror(argv[1]);
		exit(2);
	}

	stud.nume = "Mustafa Taner";
    stud.grupa = "341C1";

    rezult = grade_1(&stud, cl);
    if (rezult == NULL){
	    clnt_perror(cl, "sprc2.dfilip.xyz");
	    printf("ghinion\n");
	    exit(3);
    }

//    xdr_free(xdr_prime_result, result);
    clnt_destroy(cl);

	return 0;
}

