/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ex.h"

bool_t
xdr_student (XDR *xdrs, student *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nume, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->grupa, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rezultat (XDR *xdrs, rezultat *objp)
{
//	register int32_t *buf;
//
//	 if (!xdr_string (xdrs, &objp->s, rezultat))
//		 return FALSE;
	return TRUE;
}
