/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXPRIMES 1000

struct prime_request {
	int min;
	int max;
};
typedef struct prime_request prime_request;

struct prime_result {
	struct {
		u_int array_len;
		int *array_val;
	} array;
};
typedef struct prime_result prime_result;

#define PRIMEPROG 0x32345678
#define PRIMEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FIND_PRIMES 1
extern  prime_result * find_primes_1(prime_request *, CLIENT *);
extern  prime_result * find_primes_1_svc(prime_request *);
extern int primeprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FIND_PRIMES 1
extern  prime_result * find_primes_1();
extern  prime_result * find_primes_1_svc();
extern int primeprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_prime_request (XDR *, prime_request*);
extern  bool_t xdr_prime_result (XDR *, prime_result*);

#else /* K&R C */
extern bool_t xdr_prime_request ();
extern bool_t xdr_prime_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
