/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int isprime(int n) {
	int i;
	for (i = 2; i*i <= n; i++) {
		if ((n % i) == 0) return 0;
	}
	return 1;
}

prime_result *find_primes_1_svc(prime_request *request) {
	static prime_result  result;

	static int prime_array[MAXPRIMES];
    int i, count = 0;

    for (i = request->min; i <= request->max; i++) {
        if (isprime(i)) {
            prime_array[count++] = i;
        }
    }
    result.array.array_len = count;
    result.array.array_val = prime_array;

	return &result;
}
