/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EX_H_RPCGEN
#define _EX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct student {
	char *nume;
	char *grupa;
};
typedef struct student student;

struct rezultat {
	char *s;
};
typedef struct rezultat rezultat;

#define CHECKPROG 0x31234567
#define CHECKVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GRADE 1
extern  rezultat * grade_1(student *, CLIENT *);
extern  rezultat * grade_1_svc(student *, struct svc_req *);
extern int checkprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GRADE 1
extern  rezultat * grade_1();
extern  rezultat * grade_1_svc();
extern int checkprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_student (XDR *, student*);
extern  bool_t xdr_rezultat (XDR *, rezultat*);

#else /* K&R C */
extern bool_t xdr_student ();
extern bool_t xdr_rezultat ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EX_H_RPCGEN */
