/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ex.h"

rezultat *
grade_1_svc(student *argp, struct svc_req *rqstp)
{
	static rezultat  result;

	/*
	 * insert server code here
	 */

	return &result;
}
